export {
  stripHtml,
  getLongDescription,
  getCapacity,
  getAddress,
  buildSeoTitle,
  buildShelterDescription,
  getCity,
  getOwner,
  getContact,
  getSeason,
  getOpen24_7,
  getWheelchair,
  getPayment,
  getAccessDescription,
  getFirewood,
  getWater,
  getToilet,
  getPetsAllowed,
  getFeatures,
  getResolvedBookingModel,
  isBookable,
  isValidImageUrl,
  getGooglePhotoProxyUrl,
  getPhotoUrls,
  getResolvedPhotoUrls,
  getDisplayImageUrl,
  getResolvedDisplayImageUrl,
  hasAnyImage,
  getDisplayScore,
  isShelterPlace,
  generateFallbackDescription,
  getLocationCoords,
} from "@shared/lib/shelter-detail";

export type { ResolvedBookingModel, ShelterFeature } from "@shared/lib/shelter-detail";
